### ISSUE TITLE
Problem with DDTabSheet when selecting between tabs and drag mode activated

### ISSUE THREAD

**Issue by victorroeder** [johndevs/dragdroplayouts#13]
Hello John Ahlroos,

first of all let me thank you for your very cool DragDropLayouts!

But I would like to report a problem I faced when using the DDTabSheet (with "activated" drag mode). For example: I have two tabs (tab A and B), both with several TextFields. When tab A is active, and I alter the text in one or more TextFields, then switch to tab B, and then back to tab A again, then the previously changed TextFields are empty again. That mean's IMHO that no "value update" from client-side to server-side happens.

When I disable the drag mode, it's working fine (same when using Vaadin's origin TabSheet).

I had a look at your code, and I think that it's somewhere in the VLayoutDragDropMouseHandler.initiateDrag(...) method, but I'm not enough an expert yet to find the concrete lines.

So I would kindly ask you to have a look, as soon as you have time for that.

Many thanks and kind regards,
Victor

**Comment by victorroeder** [comment]
Hello John,

I did some further investigation on this topic since this problem occures in 1.1.x (with Vaadin 7.4.x) and 1.2.x (with Vaadin 7.6.x) as well.

Since I also increased my client-side development skills since my initial ticket :), I was able to find and fix the problem.

As already suspected, the problem was in VLayoutDragDropMouseHandler.java, method initiateDrag(), respectively initiateDragOnMove().

Referring to master branch (cloned 1-2 days ago):
I simply commented out the two lines, that stop the further propagation of the mouse event:
//        originalEvent.stopPropagation();
//        originalEvent.preventDefault();

And it works like a charme. So my question is: Is there a compelling reason why to stopPropagation and preventDefault of the MouseDownEvent?
I also backported the modified VLayoutDragDropMouseHandler, and it worked also for 1.1.x.

Just saw ticket #26 which is for 0.8.x (Vaadin 6.x). But this effect will actually also occur with current versions.

Please let me know your opinion.

Many thanks,
Victor

**Comment by victorroeder** [comment]
>  Is there a compelling reason why to stopPropagation and preventDefault of the MouseDownEvent?

Ok, the text selection that would happen if the mouse down event is not stopped, I see.

I try to do some further investigations.

Kind regards,
Victor

**Comment by victorroeder** [comment]
Ok, I added to VLayoutDragDropMouseHandler.initiateDragOnMove(...) several conditions under which the propagation of the MouseDownEvent is not stopped.

I did also some visual tests with your demo and my application and it looks very good in my eyes.

Since I'm new to Git(Hub), I would like to ask how I could provide you the changes so that you can test them as well? Simply push?

Many thanks,
Victor

**Comment by mjungwir** [comment]
Create a pull request. This will put the changes in a saved place and the owners of the repo can review them and decide if they would like to integrate them.

[https://help.github.com/articles/creating-a-pull-request/](url)

**Comment by victorroeder** [comment]
Created pull request. I hope did it correctly. It has #46.

Tried to do it directly out of Netbeans but did not find a way. So I cloned the repo to my account, created a new branch, pushed to "my" repo dragdroplayouts and created the pull request from GitHub.

Thanks for checking my changes,
Victor

**Comment by johndevs** [comment]
Merged in 36196c95951e6b9b4a3bc11aae3f7ea65de33cef.

**Comment by johndevs** [comment]
@victorroeder Thanks for reporting *and* fixing the issue!
