### ISSUE TITLE
Compile widgetset fails with Vaadin 7.4.0.beta3

### ISSUE THREAD

**Issue by markoradinovic** [johndevs/dragdroplayouts#27]
Hi, 
widgetset compilation fails with Vaadin 7.4.0.beta3.

[INFO] Using com.vaadin:vaadin-client-compiler version 7.4.0.beta3
[INFO] Loading inherited module 'com.zipsoft.cloud.ui.admin.AppWidgetSet'
[INFO]    Loading inherited module 'fi.jasoft.dragdroplayouts.DragDropLayoutsWidgetSet'
[INFO]       [ERROR] Line 6: Value 'opera' in not a valid value for property 'user.agent'

**Comment by sblommers** [comment]
Same here

**Comment by markoradinovic** [comment]
As a workaround solution I created DragDropLayoutsWidgetSet.gwt.xml in package fi.jasoft.dragdroplayouts with modifications

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Vaadin//DTD Vaadin 7//EN" "https://raw.github.com/vaadin/gwt/master/distro-source/core/src/gwt-module.dtd">
<!-- WS Compiler: manually edited -->
<module>
        <inherits name="com.vaadin.DefaultWidgetSet" />
        <set-property name="user.agent" value="ie8,ie9,gecko1_8,safari,ie10" />
        <source path="client" />
        <source path="shared" />
        <stylesheet src="fi_jasoft_dragdroplayouts/dragdroplayouts.css" />
        <collapse-all-properties />
        <set-property name="compiler.useSymbolMaps" value="true" />
</module>
```

**Comment by sblommers** [comment]
Perfect!! Thank you :)
Op 31 jan. 2015 01:11 schreef "Marko Radinovic" <notifications@github.com>:

**Comment by markathomas** [comment]
A simpler solution is to add

<extend-property name="user.agent" values="opera" fallback-value="safari" />

to your widgetset

**Comment by sblommers** [comment]
Hi Mark, thank you for the fix. Unfortunately a 1.1.2 build exists on vaadin maven that still has the opera so build fails with 1.1.2 release. Check the download on vaadin website there you can also see that the gwt.xml contains opera. Can you re-open this issue?

**Comment by johndevs** [comment]
@sblommers The one that is found in the vaadin maven repository should be the same that you can download directly from https://vaadin.com/directory#addon/dragdroplayouts. If you open that jar and look at the DragDropLayoutsWidgetSet.gwt.xml found in that jar then you'll see that *opera* is missing from there.

**Comment by sblommers** [comment]
Dude, there is nothing wrong with my eyes, and also not with my compiler.

**Comment by johndevs** [comment]
Yes, you're right of course. Was looking at a development snapshot.. :blush:

**Comment by johndevs** [comment]
Something was wrong with the release build. A new version that works should now be available.

**Comment by sblommers** [comment]
@johndevs thanks for your quick response :+1:
