### ISSUE TITLE
Limiting which visual component is used when moving inner layouts 

### ISSUE THREAD

**Issue by mjungwir** [johndevs/dragdroplayouts#44]
This is more of an enhancement request I guess, but you can use the inner layouts example code to see what I'm desribing: http://apps-johndevs.rhcloud.com/dragdroplayouts/#!dd-dragging-layouts

In some situations I'd like to be able to make the whole draggable component the "cloned" visible element when I'm dragging the item around. What I'm trying to do now is create a visual "card," if you will, where there is a horizontal layout with many labels within it. As with the provided example in the project if I click a button to drag, that button is the visible component that moves around. Once I drop the component the entire VerticalLayout is what is actually moved. There may be times when this is preferred, but it would be nice to make it such that when any of the components are dragged the entire components' layout that will be moved is the "cloned" visual element.

I hope that is clear. I haven't taken a great deal of time to investigate what this would take. Perhaps a new LayoutDragMode and the corresponding code changes to accomodate? If I'm lucky there is a way to do this already. If not, let me know if anyone has any clever ideas and I'd be willing to take a crack at it.

**Comment by mjungwir** [comment]
I'm still not too far in spending time on this, but I did find that I believe I just have to find how your framework ties into Vaadin's DragStartMode. Here's what I want. https://vaadin.com/api/7.6.1/com/vaadin/ui/DragAndDropWrapper.DragStartMode.html#WRAPPER

As seen on their example: http://demo.vaadin.com/sampler/#ui/drag-drop/drag-components

I'm wondering at this point if it is purposeful that the LayoutDragMode basically mirrors Vaadin's DragStartMode but it is missing the Wrapper equivalent. I'll keep digging...

**Comment by mjungwir** [comment]
I achieved what I was looking for by using a DragImageProvider. It appears that for the DragFilter and DragImageProvider only the direct chiled components are processed, i.e. not grand children etc.

Building off of your example again below. 

```java
final DDAbsoluteLayout layout = new DDAbsoluteLayout();
layout.setDragImageProvider(new DragImageProvider() {
    @Override
    public Component getDragImage(Component component) {
        return component;
    }
});
```

I think it'd be slick to accomplish this via the setDragMode method, but maybe that's just me. I might pursue this to see if it makes sense. I think the advantage is not having to make all these anonymous inner classes (which isn't that bad; with Java 8 especially). However maybe more people would self discover this possibility if it were avaible via the DragMode enum?

**Comment by johndevs** [comment]
I think this should be the default behaviour actually. 

When dragging a button that is inside a layout that is not draggable the whole, non-draggable, layout should be dragged. The current behaviour looks like a bug.

**Comment by johndevs** [comment]
The default fixed so the workaround will not be needed in the next maintenance version (1.2.1)

**Comment by mjungwir** [comment]
Thanks very much, @johndevs ! I'm very much looking forward to 1.2.1 along with other changes like what you did in adf14e2fb4d7490b4ea519ca71b936baad9c2637
