### ISSUE TITLE
Selected components become droppable items.

### ISSUE THREAD

**Issue by mjungwir** [johndevs/dragdroplayouts#47]
Basically it seems like when clicking over something you can select some elements in the background and this makes them a draggable thing?  With the 1.2 draganddrop addon I can’t reproduce the problem because every inner component (Labels) has a drop target/slot so I can’t seem to highlight the text. This was something he fixed with 1.2.1 and perhaps introduced/revealed this issue.

[dragdrop.zip](https://github.com/johndevs/dragdroplayouts/files/138199/dragdrop.zip)
Here’s the sample project and what happens: [http://screencast.com/t/5b27WCmpxo] If you click somewhere to deselect the element before trying to drag again it doesn’t seem to drag the highlighted element around.

I don’t know if this is a clue but I will note that the problem seemed mostly reproducible the whole time, however not until I added the drop handlers to the sample project would the letter drop into place. Before that it seemed like something was now the drag item as the normal component image wasn’t showing up.

It seems to be exacerbated though when the Vaadin app is embedded on the page. Our app embeds the Vaadin stuff we have and it’s causing quite a problem as for reasons not yet discovered it seems to select a bunch of the layout when clicking on an item to drag it. [http://screencast.com/t/axjAKjK6e]

I tried to get around this by making the layout disable user-select in CSS. While this makes it better some of the copyright at the bottom of the page from the page that Vaadin is embedded in gets selected and moved around.

I'm suspicious of both selecting something making it an independent draggable item of sorts and if somehow the GWT code of the addon is responsible for selecting things when you click on an item. But that's not really based on any evidence.

**Comment by victorroeder** [comment]
I try to take care of it...

**Comment by mjungwir** [comment]
Thanks for working on this @victorroeder and @johndevs. I look forward to the release

**Comment by victorroeder** [comment]
Hi @mjungwir,
just saw that version 1.2.2 has been released at https://vaadin.com/directory#!addon/dragdroplayouts.
Could you please give it a try, wether the text selection disappeared or not? (Pls. remember to re-compile your widgetset).
Many thanks,
Victor

**Comment by mjungwir** [comment]
@victorroeder 
I just tried it out today and it works great! Thanks for fixing this for me.
