### ISSUE TITLE
Button Click inside any DDLayout on Mobile Devices does not work

### ISSUE THREAD

**Issue by pk1057** [johndevs/dragdroplayouts#51]
Hello,
we discovered that a Button contained in any DDLayout does not fire reliable a clicked event when the page is displayed on a mobile touch device.

This can easily simulated when you use chrome , enable developer mode and switch for example to the ipad device, then there are no button submit events fired.

**Comment by pk1057** [comment]
I examined the problem a little bit further.
The Button we are using is a call extending button and the be added to a ddPanel.
But if a change my class in the way that i return a button, not the class itself the button is working ...
It's very strange
The attached code shows the "workaround" version stripped down with touch detection and generation of a plain button object instead of the class extending a button.
I checked with a modifed version where i replaced the ddpanel with a panel and it works as expected.
Any clues or pointers where to debug ?

```
public class ShortcutIcon  extends Button {
    
    private int posX = 0;
    private int posY = 0;
    private String shortcutName = "";
    private Button b = null;
    
    public ShortcutIcon() {
        if (UI.getCurrent().getPage().getWebBrowser().isTouchDevice()) {
             b = new Button() {
                 @Override
                 public void setDescription(String stgring) {
                 }
             };
        } else b = this;
    }    
    public Button getButton() {
        return b;
    }

```

**Comment by pk1057** [comment]
Ok i digged further in the code.
It seems the problem lies in VLayoutDragDropMouseHandler.
This module uses the TouchEvent, but this one does not distinguish between just touched and move.
So i switched inside this class from onTouch to onToucMove and it works now with my IPAD as expected.

**Comment by johndevs** [comment]
@pk1057 Would you mind doing a PR with the code change you needed to do to make it work?

**Comment by pk1057** [comment]
In Progress, will do it in the next view days.

peter
