### ISSUE TITLE
DDTabSheet not dragging using 1.3.1 under Vaadin 7.7.0, but does using previous 1.2

### ISSUE THREAD

**Issue by OpenESignForms** [johndevs/dragdroplayouts#69]
I noted that you created version 1.3.1 for use under Vaadin 7.7.0, but if I remove the 1.2 version and use the 1.3.1, recompile my widgetsets, my tabs are not longer draggable under any browser.

If I then remove 1.3.1 and revert back to 1.2, while still using Vaadin 7.7.0, and recompile the widgetsets, it seems to work again.

**Comment by johndevs** [comment]
Hi,

The Tabsheet at http://apps-johndevs.rhcloud.com/dragdroplayouts/#!dd-tabsheet seems to work fine. That runs on 7.7 and 1.3.1. 

Could you ensure that your widgetset is corrently in use by adding ?debug to the url and check the versions + widgetsetname?

![selection_067](https://cloud.githubusercontent.com/assets/1967917/18129590/0ca2009c-6f94-11e6-8052-8f10e10b567f.png)

**Comment by OpenESignForms** [comment]
Well, it shows 7.7.0 as expected because I am familiar with recompiling widgetsets -- I do it as I switched between your 1.3.1 and 1.2 versions repeatedly <smile>.

But I did just note that my webapp's widgetset.gwt.xml file is being updated when I recompile the widgetset under 1.3.1 that removes the line:

    <inherits name="fi.jasoft.dragdroplayouts.DragDropLayoutsWidgetSet" />

And the compilation statements seem weird under 1.3.1:

Widgetsets found from classpath:

	org.vaadin.openesignforms.ckeditor.widgetset.VaadinCKEditorWidgetset in jar:file:/Users/yozons/Documents/project/open-eSignFormsVaadin/WebContent/WEB-INF/lib/vaadinckeditor7.10.10.jar!/
	org.vaadin.hene.popupbutton.widgetset.PopupbuttonWidgetset in jar:file:/Users/yozons/Documents/project/open-eSignFormsVaadin/WebContent/WEB-INF/lib/popupbutton-2.6.0.jar!/
	com.esignforms.open.vaadin.widgetset.Open_esignformsvaadinWidgetset in file:/Users/yozons/Documents/project/open-eSignFormsVaadin/src
	org.vaadin.jouni.animator.AnimatorWidgetset in jar:file:/Users/yozons/Documents/project/open-eSignFormsVaadin/WebContent/WEB-INF/lib/animator-1.7.4.jar!/
	org.vaadin.peter.buttongroup.ButtonGroupWidgetset in jar:file:/Users/yozons/Documents/project/open-eSignFormsVaadin/WebContent/WEB-INF/lib/ButtonGroup-2.3.jar!/
	org.vaadin.resetbuttonfortextfield.WidgetSet in jar:file:/Users/yozons/Documents/project/open-eSignFormsVaadin/WebContent/WEB-INF/lib/resetbuttonfortextfield-1.2.1.jar!/
	com.vaadin.DefaultWidgetSet in jar:file:/Users/yozons/Documents/project/open-eSignFormsVaadin/WebContent/WEB-INF/lib/dragdroplayouts-1.3.1.jar!/

Note that drag and drop is showing com.vaadin.DefaultWidgetSet instead of the expected org.vaadin.resetbuttonfortextfield.WidgetSet

When I revert back to the 1.2 version of your JAR, it puts back the line <inherits name="fi.jasoft.dragdroplayouts.DragDropLayoutsWidgetSet" /> into my widgetset.gwt.xml file and the compilation seems to show all as expected:

	org.vaadin.openesignforms.ckeditor.widgetset.VaadinCKEditorWidgetset in jar:file:/Users/yozons/Documents/project/open-eSignFormsVaadin/WebContent/WEB-INF/lib/vaadinckeditor7.10.10.jar!/
	org.vaadin.hene.popupbutton.widgetset.PopupbuttonWidgetset in jar:file:/Users/yozons/Documents/project/open-eSignFormsVaadin/WebContent/WEB-INF/lib/popupbutton-2.6.0.jar!/
	fi.jasoft.dragdroplayouts.DragDropLayoutsWidgetSet in jar:file:/Users/yozons/Documents/project/open-eSignFormsVaadin/WebContent/WEB-INF/lib/dragdroplayouts-1.2.jar!/
	com.esignforms.open.vaadin.widgetset.Open_esignformsvaadinWidgetset in file:/Users/yozons/Documents/project/open-eSignFormsVaadin/src
	org.vaadin.jouni.animator.AnimatorWidgetset in jar:file:/Users/yozons/Documents/project/open-eSignFormsVaadin/WebContent/WEB-INF/lib/animator-1.7.4.jar!/
	org.vaadin.peter.buttongroup.ButtonGroupWidgetset in jar:file:/Users/yozons/Documents/project/open-eSignFormsVaadin/WebContent/WEB-INF/lib/ButtonGroup-2.3.jar!/
	org.vaadin.resetbuttonfortextfield.WidgetSet in jar:file:/Users/yozons/Documents/project/open-eSignFormsVaadin/WebContent/WEB-INF/lib/resetbuttonfortextfield-1.2.1.jar!/
	com.vaadin.DefaultWidgetSet in jar:file:/Users/yozons/.ivy2/cache/com.vaadin/vaadin-client/jars/vaadin-client-7.7.0.jar!/

So I am guessing something changed with the widgetset name in the 1.3.1 JAR that is causing me issues when I recompile widgetsets in Eclipse (I did an update so I should have the latest vaadin eclipse plugin).  Any ideas what might be causing this?

**Comment by johndevs** [comment]
@OpenESignForms 
As a workaround you can add ```<!-- WS Compiler: manually edited -->``` above the ```<module>```. It will keep the compiler from not removing the inherit tag.

I'll check if the build of the 1.3.1 version of the addon has somehow failed and failed to include the necessary inherit metadata.

**Comment by johndevs** [comment]
Should be fixed now in 1.3.2. 

Thanks for reporting this issue so quickly!

**Comment by OpenESignForms** [comment]
Thanks. That did the trick!
