### ISSUE TITLE
Image onClick even not working from IPAD when wrapped in a DDHorizontalLayout

### ISSUE THREAD

**Issue by sajid2045** [johndevs/dragdroplayouts#7]
The following code works fine in Chrome Desktop but the clickListener is never fired on Chrome in IPAD.

Image newImage = new Image("", img.getSource());
						newImage.setHeight(1, Unit.INCH);
						newImage.setWidth(1, Unit.INCH);
						imageStrip.addComponent(newImage);
						
						
						com.vaadin.event.MouseEvents.ClickListener stripClipListener = new com.vaadin.event.MouseEvents.ClickListener(){

							@Override
							public void click(
									com.vaadin.event.MouseEvents.ClickEvent event) {
								Image panelImage = new Image();
								
								panelImage.setSource(((Image) event.getSource()).getSource());
								
								panelImage.setSizeFull();
								
								imageHolder.setContent(panelImage);
								
							}};
						newImage.addClickListener(stripClipListener);

**Comment by johndevs** [comment]
This issue has been stale for a long while. Please open if this is still relevant.
